################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
S_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
ASM_DEPS := 
EEPROM_IMAGE := 
FLASH_IMAGE := 
ELFS := 
LSS := 
S_DEPS := 
SIZEDUMMY := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
services/wol \
services/watchcat \
services/watchasync \
services/vnc \
services/upnp \
services/tftp \
services/stella \
services/pam \
services/ntp \
services/motd \
services/moodlight \
services/jabber \
services/httpd \
services/glcdmenu/menu-interpreter \
services/glcdmenu \
services/echo \
services/dyndns \
services/curtain \
services/cron \
services/clock \
services/bulbdial \
services/appsample \
scripts/lxdialog \
protocols/zbus \
protocols/yport \
protocols/ustream \
protocols/usb/usbdrv \
protocols/usb \
protocols/uip \
protocols/udpstella \
protocols/udpcurtain \
protocols/udpIO \
protocols/twitter \
protocols/to1 \
protocols/syslog \
protocols/soap \
protocols/snmp \
protocols/smtp \
protocols/sms77 \
protocols/serial_line_log \
protocols/nmea \
protocols/netstat \
protocols/mysql \
protocols/msr1 \
protocols/modbus \
protocols/mdns_sd \
protocols/irc \
protocols/httplog \
protocols/ecmd/via_usart \
protocols/ecmd/via_udp \
protocols/ecmd/via_tcp \
protocols/ecmd/via_i2c \
protocols/ecmd/sender \
protocols/ecmd \
protocols/dns \
protocols/dmx \
protocols/cw \
protocols/bootp \
protocols/artnet \
. \
mcuf \
mcuf/image \
mcuf/borg-16 \
hardware/zacwire \
hardware/ultrasonic \
hardware/storage/sd_reader \
hardware/storage/dataflash \
hardware/sram \
hardware/sms \
hardware/sht \
hardware/radio/rfm12 \
hardware/radio/fs20 \
hardware/pwm \
hardware/onewire \
hardware/lcd/s1d15g10 \
hardware/lcd/s1d13305 \
hardware/lcd \
hardware/lcd/ST7626 \
hardware/isdn \
hardware/ir/rc5 \
hardware/io_expander \
hardware/input/ps2 \
hardware/input \
hardware/input/buttons \
hardware/i2c/slave \
hardware/i2c/master \
hardware/hbridge \
hardware/ethernet \
hardware/dac \
hardware/clock/dcf77 \
hardware/camera \
hardware/avr \
hardware/adc \
hardware/adc/kty \
hardware/adc/ads7822 \
embed \
core/vfs \
core/util \
core \
core/tty \
core/portio \
core/host \
core/gui \
core/crypto \
control6 \
contrib/zbus-serial-host \
contrib/webscripts \
contrib/usb_net \
contrib/udpCurtain \
contrib/mcuf \
contrib/libecmd/rfm12ask_2272 \
contrib/libecmd/interactive \
contrib/kty81-110 \
contrib/ecmd_usb \

