/* Autogenerated File */
#define OUTPUT 0
#define INPUT 1
#define LOW 0
#define HIGH 1
const char named_pin_text9158[] PROGMEM = "p1";
const char named_pin_text6249[] PROGMEM = "p2";
const char named_pin_text18547[] PROGMEM = "p3";
const char named_pin_text23633[] PROGMEM = "p4";

const struct PinConfiguration portio_pincfg[] PROGMEM = {
    /*  port	pin	input	reverse? */
	{	0,	0,	OUTPUT,	HIGH,	named_pin_text9158 }, 	/* p1	*/ 
	{	0,	1,	OUTPUT,	HIGH,	named_pin_text6249 }, 	/* p2	*/ 
	{	0,	2,	OUTPUT,	HIGH,	named_pin_text18547 }, 	/* p3	*/ 
	{	0,	3,	OUTPUT,	HIGH,	named_pin_text23633 }, 	/* p4	*/ 

    /* mark the end of the list */
    { 255, 255, 255, 255, NULL}
};
