/* Autogenerated File*/
#ifndef NAMEDPIN_CONF
#define NAMEDPIN_CONF

#define p1_PORT A
#define p1_PIN 0
#define p2_PORT A
#define p2_PIN 1
#define p3_PORT A
#define p3_PIN 2
#define p4_PORT A
#define p4_PIN 3
#endif
