/* Autogenerated File */
#define OUTPUT 0
#define INPUT 1
#define LOW 0
#define HIGH 1
const char named_pin_text29970[] PROGMEM = "p1";
const char named_pin_text6556[] PROGMEM = "p2";
const char named_pin_text10432[] PROGMEM = "p3";
const char named_pin_text3553[] PROGMEM = "p4";

const struct PinConfiguration portio_pincfg[] PROGMEM = {
    /*  port	pin	input	reverse? */
	{	0,	0,	OUTPUT,	HIGH,	named_pin_text29970 }, 	/* p1	*/ 
	{	0,	1,	OUTPUT,	HIGH,	named_pin_text6556 }, 	/* p2	*/ 
	{	0,	2,	OUTPUT,	HIGH,	named_pin_text10432 }, 	/* p3	*/ 
	{	0,	3,	OUTPUT,	HIGH,	named_pin_text3553 }, 	/* p4	*/ 

    /* mark the end of the list */
    { 255, 255, 255, 255, NULL}
};
